AAX SDK: AAX_CDecibelDisplayDelegateDecorator< T > Class Template Reference
AAX_CDecibelDisplayDelegateDecorator< T > Class Template Reference
AAX SDK Manual » AAX Library features » Parameter Manager » Display delegates » Display delegate decorators
#include <AAX_CDecibelDisplayDelegateDecorator.h>
Description
template<typename T>
class AAX_CDecibelDisplayDelegateDecorator< T >
A percent decorator conforming to AAX_IDisplayDelegateDecorator.
This class is an AAX_IDisplayDelegateDecorator, meaning that it acts as a wrapper for other display delegates or concrete display types. For more information about display delegate decorators in AAX, see Display delegate decorators
The behavior of this class it to provide conversion to and from dB values. It performs a decibel conversion on the square of the provided value (i.e. 20 log) before passing the value on to a concrete display delegate to get a value string. This class then appends the "dB" suffix to signify that the value was converted. This allows something like a gain value to remain internally linear at all times even though its display is converted to decibels.
The inverse is also supported; this class can convert a decibel-formatted string into its associated real value. The string will first be converted to a number, then that number will have the inverse dB calculation applied to it to retrieve the parameter's real value.
Public Member Functions
AAX_CDecibelDisplayDelegateDecorator (const AAX_IDisplayDelegate< T > &displayDelegate)
virtual AAX_CDecibelDisplayDelegateDecorator< T > * Clone () const AAX_OVERRIDE
Constructs and returns a copy of the display delegate decorator.
virtual bool ValueToString (T value, AAX_CString *valueString) const AAX_OVERRIDE
Converts a string to a real parameter value.
virtual bool ValueToString (T value, int32_t maxNumChars, AAX_CString *valueString) const AAX_OVERRIDE
Converts a string to a real parameter value with a size constraint.
virtual bool StringToValue (const AAX_CString &valueString, T *value) const AAX_OVERRIDE
Converts a string to a real parameter value.
Public Member Functions inherited from AAX_IDisplayDelegateDecorator< T >
AAX_IDisplayDelegateDecorator (const AAX_IDisplayDelegate< T > &displayDelegate)
Constructor.
AAX_IDisplayDelegateDecorator (const AAX_IDisplayDelegateDecorator &other)
Copy constructor.
virtual ~AAX_IDisplayDelegateDecorator ()
Virtual destructor.
Public Member Functions inherited from AAX_IDisplayDelegateBase
virtual ~AAX_IDisplayDelegateBase ()
Virtual destructor.
Constructor & Destructor Documentation
template<typename T > AAX_CDecibelDisplayDelegateDecorator< T >::AAX_CDecibelDisplayDelegateDecorator (const AAX_IDisplayDelegate< T > & displayDelegate)
Member Function Documentation
template<typename T > AAX_CDecibelDisplayDelegateDecorator< T > * AAX_CDecibelDisplayDelegateDecorator< T >::Clone () const virtual
Constructs and returns a copy of the display delegate decorator.
In general, this method's implementation can use a simple copy constructor:
template <typename T>
AAX_CSubclassDisplayDelegate<T>*    AAX_CSubclassDisplayDelegate<T>::Clone() const
{
    return new AAX_CSubclassDisplayDelegate(*this);
}
Note
This is an idiomatic method in the decorator pattern, so watch for potential problems if this method is ever changed or removed.
Reimplemented from AAX_IDisplayDelegateDecorator< T >.
template<typename T > bool AAX_CDecibelDisplayDelegateDecorator< T >::ValueToString (T value, AAX_CString * valueString) const virtual
Converts a string to a real parameter value.
Override of the AAX_IDisplayDelegate implementation to call into the wrapped object. Display delegate decorators should call into this implementation to pass ValueToString() calls on to the wrapped object after applying their own value-to-string decoration.
Parameters
[in] valueString The string that will be converted
[out] value The real parameter value corresponding to valueString
Return values
true The string conversion was successful
false The string conversion was unsuccessful
Reimplemented from AAX_IDisplayDelegateDecorator< T >.
References AAX_IDisplayDelegateDecorator< T >::ValueToString().
template<typename T > bool AAX_CDecibelDisplayDelegateDecorator< T >::ValueToString (T value, int32_t maxNumChars, AAX_CString * valueString) const virtual
Converts a string to a real parameter value with a size constraint.
Override of the AAX_IDisplayDelegate implementation to call into the wrapped object. Display delegate decorators should call into this implementation to pass ValueToString() calls on to the wrapped object after applying their own value-to-string decoration.
Parameters
[in] valueString The string that will be converted
[in] maxNumChars Size hint for the desired maximum number of characters in the string (not including null termination)
[out] value The real parameter value corresponding to valueString
Return values
true The string conversion was successful
false The string conversion was unsuccessful
Reimplemented from AAX_IDisplayDelegateDecorator< T >.
References AAX_CString::Append(), AAX_CString::Length(), and AAX_IDisplayDelegateDecorator< T >::ValueToString().
template<typename T > bool AAX_CDecibelDisplayDelegateDecorator< T >::StringToValue (const AAX_CString & valueString, T * value) const virtual
Converts a string to a real parameter value.
Override of the DisplayDecorator implementation to call into the wrapped object. Display delegate decorators should call into this implementation to pass StringToValue() calls on to the wrapped object after applying their own string-to-value decoding.
Parameters
[in] valueString The string that will be converted
[out] value The real parameter value corresponding to valueString
Return values
true The string conversion was successful
false The string conversion was unsuccessful
Reimplemented from AAX_IDisplayDelegateDecorator< T >.
References AAX_CString::Length(), AAX_IDisplayDelegateDecorator< T >::StringToValue(), and AAX_CString::SubString().
The documentation for this class was generated from the following file:
AAX_CDecibelDisplayDelegateDecorator.h