AAX SDK: AAX_CStatelessParameter Class Reference
AAX_CStatelessParameter Class Reference
#include <AAX_CParameter.h>
Description
A stateless parameter implementation.
This can be useful for mapping event triggers to control surface buttons or to GUI switches.
Public Member Functions
AAX_CStatelessParameter (AAX_CParamID identifier, const AAX_IString &name, const AAX_IString &inValueString)
AAX_CStatelessParameter (const AAX_IString &identifier, const AAX_IString &name, const AAX_IString &inValueString)
virtual ~AAX_CStatelessParameter ()
virtual AAX_IParameterValue * CloneValue () const
Clone the parameter's value to a new AAX_IParameterValue object.
virtual void SetType (AAX_EParameterType)
Sets the type of this parameter.
virtual AAX_EParameterType GetType () const
Returns the type of this parameter as an AAX_EParameterType.
virtual void SetOrientation (AAX_EParameterOrientation)
Sets the orientation of this parameter.
virtual AAX_EParameterOrientation GetOrientation () const
Returns the orientation of this parameter.
virtual void SetTaperDelegate (AAX_ITaperDelegateBase &, bool)
Sets the parameter's taper delegate.
virtual void SetDisplayDelegate (AAX_IDisplayDelegateBase &)
Sets the parameter's display delegate.
Identification methods
virtual AAX_CParamID Identifier () const
Returns the parameter's unique identifier.
virtual void SetName (const AAX_CString &name)
Sets the parameter's display name.
virtual const AAX_CString & Name () const
Returns the parameter's display name.
virtual void AddShortenedName (const AAX_CString &name)
Sets the parameter's shortened display name.
virtual const AAX_CString & ShortenedName (int32_t iNumCharacters) const
Returns the parameter's shortened display name.
virtual void ClearShortenedNames ()
Clears the internal list of shortened display names.
Automation methods
virtual bool Automatable () const
Returns true if the parameter is automatable, false if it is not.
virtual void SetAutomationDelegate (AAX_IAutomationDelegate *iAutomationDelegate)
Sets the automation delegate (if one is required)
virtual void Touch ()
Signals the automation system that a control has been touched.
virtual void Release ()
Signals the automation system that a control has been released.
Taper methods
virtual void SetNormalizedValue (double)
Sets a parameter value using it's normalized representation.
virtual double GetNormalizedValue () const
Returns the normalized representation of the parameter's current real value.
virtual void SetNormalizedDefaultValue (double)
Sets the parameter's default value using its normalized representation.
virtual double GetNormalizedDefaultValue () const
Returns the normalized representation of the parameter's real default value.
virtual void SetToDefaultValue ()
Restores the state of this parameter to its default value.
virtual void SetNumberOfSteps (uint32_t)
Sets the number of discrete steps for this parameter.
virtual uint32_t GetNumberOfSteps () const
Returns the number of discrete steps used by the parameter.
virtual uint32_t GetStepValue () const
Returns the current step for the current value of the parameter.
virtual double GetNormalizedValueFromStep (uint32_t) const
Returns the normalized value for a given step.
virtual uint32_t GetStepValueFromNormalizedValue (double) const
Returns the step value for a normalized value of the parameter.
virtual void SetStepValue (uint32_t)
Returns the current step for the current value of the parameter.
Display methods
This functionality is most often used by GUIs, but can also be useful for state serialization.
virtual bool GetValueString (AAX_CString *valueString) const
Serializes the parameter value into a string.
virtual bool GetValueString (int32_t, AAX_CString *valueString) const
Serializes the parameter value into a string, size hint included.
virtual bool GetNormalizedValueFromBool (bool, double *normalizedValue) const
Converts a bool to a normalized parameter value.
virtual bool GetNormalizedValueFromInt32 (int32_t, double *normalizedValue) const
Converts an integer to a normalized parameter value.
virtual bool GetNormalizedValueFromFloat (float, double *normalizedValue) const
Converts a float to a normalized parameter value.
virtual bool GetNormalizedValueFromDouble (double, double *normalizedValue) const
Converts a double to a normalized parameter value.
virtual bool GetNormalizedValueFromString (const AAX_CString &, double *normalizedValue) const
Converts a given string to a normalized parameter value.
virtual bool GetBoolFromNormalizedValue (double, bool *value) const
Converts a normalized parameter value to a bool representing the corresponding real value.
virtual bool GetInt32FromNormalizedValue (double, int32_t *) const
Converts a normalized parameter value to an integer representing the corresponding real value.
virtual bool GetFloatFromNormalizedValue (double, float *) const
Converts a normalized parameter value to a float representing the corresponding real value.
virtual bool GetDoubleFromNormalizedValue (double, double *) const
Converts a normalized parameter value to a double representing the corresponding real value.
virtual bool GetStringFromNormalizedValue (double, AAX_CString &valueString) const
Converts a normalized parameter value to a string representing the corresponding real value.
virtual bool GetStringFromNormalizedValue (double normalizedValue, int32_t, AAX_CString &valueString) const
Converts a normalized parameter value to a string representing the corresponding real, size hint included. value.
virtual bool SetValueFromString (const AAX_CString &newValueString)
Converts a string to a real parameter value and sets the parameter to this value.
Typed accessors
virtual bool GetValueAsBool (bool *value) const
Retrieves the parameter's value as a bool.
virtual bool GetValueAsInt32 (int32_t *) const
Retrieves the parameter's value as an int32_t.
virtual bool GetValueAsFloat (float *) const
Retrieves the parameter's value as a float.
virtual bool GetValueAsDouble (double *) const
Retrieves the parameter's value as a double.
virtual bool GetValueAsString (AAX_IString *) const
Retrieves the parameter's value as a string.
virtual bool SetValueWithBool (bool)
Sets the parameter's value as a bool.
virtual bool SetValueWithInt32 (int32_t)
Sets the parameter's value as an int32_t.
virtual bool SetValueWithFloat (float)
Sets the parameter's value as a float.
virtual bool SetValueWithDouble (double)
Sets the parameter's value as a double.
virtual bool SetValueWithString (const AAX_IString &value)
Sets the parameter's value as a string.
Host interface methods
virtual void UpdateNormalizedValue (double)
Sets the parameter's state given a normalized value.
Public Member Functions inherited from AAX_IParameter
virtual ~AAX_IParameter ()
Virtual destructor.
Protected Attributes
AAX_CStringAbbreviations mNames
AAX_CString mID
AAX_IAutomationDelegate * mAutomationDelegate
AAX_CString mValueString
Constructor & Destructor Documentation
AAX_CStatelessParameter::AAX_CStatelessParameter (AAX_CParamID identifier, const AAX_IString & name, const AAX_IString & inValueString) inline
AAX_CStatelessParameter::AAX_CStatelessParameter (const AAX_IString & identifier, const AAX_IString & name, const AAX_IString & inValueString) inline
virtual AAX_CStatelessParameter::~AAX_CStatelessParameter () inline virtual
Member Function Documentation
virtual AAX_IParameterValue* AAX_CStatelessParameter::CloneValue () const inline virtual
Clone the parameter's value to a new AAX_IParameterValue object.
The returned object is independent from the AAX_IParameter. For example, changing the state of the returned object will not result in a change to the original AAX_IParameter.
Implements AAX_IParameter.
virtual AAX_CParamID AAX_CStatelessParameter::Identifier () const inline virtual
Returns the parameter's unique identifier.
This unique ID is used by the Parameter Manager and by outside applications to uniquely identify and target control messages. This value may not be changed after the parameter has been constructed.
Implements AAX_IParameter.
References AAX_CString::CString(), and mID.
Referenced by Release(), SetAutomationDelegate(), and Touch().
virtual void AAX_CStatelessParameter::SetName (const AAX_CString & name) inline virtual
Sets the parameter's display name.
This name is used for display only, it is not used for indexing or identifying the parameter This name may be changed after the parameter has been created, but display name changes may not be recognized by all AAX hosts.
Parameters
[in] name Display name that will be assigned to the parameter
Implements AAX_IParameter.
References mNames, and AAX_CStringAbbreviations::SetPrimary().
virtual const AAX_CString& AAX_CStatelessParameter::Name () const inline virtual
Returns the parameter's display name.
Note
This method returns a const reference in order to prevent a string copy. Do not cast away the const to change this value.
Implements AAX_IParameter.
References mNames, and AAX_CStringAbbreviations::Primary().
virtual void AAX_CStatelessParameter::AddShortenedName (const AAX_CString & name) inline virtual
Sets the parameter's shortened display name.
This name is used for display only, it is not used for indexing or identifying the parameter These names show up when the host asks for shorter length parameter names for display on Control Surfaces or other string length constrained situations.
Parameters
[in] name Shortened display names that will be assigned to the parameter
Implements AAX_IParameter.
References AAX_CStringAbbreviations::Add(), and mNames.
virtual const AAX_CString& AAX_CStatelessParameter::ShortenedName (int32_t iNumCharacters) const inline virtual
Returns the parameter's shortened display name.
Note
This method returns a const reference in order to prevent a string copy. Do not cast away the const to change this value.
Implements AAX_IParameter.
References AAX_CStringAbbreviations::Get(), and mNames.
virtual void AAX_CStatelessParameter::ClearShortenedNames () inline virtual
Clears the internal list of shortened display names.
Implements AAX_IParameter.
References AAX_CStringAbbreviations::Clear(), and mNames.
virtual bool AAX_CStatelessParameter::Automatable () const inline virtual
Returns true if the parameter is automatable, false if it is not.
Note
Subclasses that return true in this method must support host-based automation.
Implements AAX_IParameter.
virtual void AAX_CStatelessParameter::SetAutomationDelegate (AAX_IAutomationDelegate * iAutomationDelegate) inline virtual
Sets the automation delegate (if one is required)
Parameters
[in] iAutomationDelegate A reference to the parameter manager's automation delegate interface
Implements AAX_IParameter.
References Identifier(), mAutomationDelegate, AAX_IAutomationDelegate::RegisterParameter(), and AAX_IAutomationDelegate::UnregisterParameter().
virtual void AAX_CStatelessParameter::Touch () inline virtual
Signals the automation system that a control has been touched.
Call this method in response to GUI events that begin editing, such as a mouse down. After this method has been called you are free to call SetNormalizedValue() as much as you need, e.g. in order to respond to subsequent mouse moved events. Call Release() to free the parameter for updates from other controls.
Implements AAX_IParameter.
References Identifier(), mAutomationDelegate, and AAX_IAutomationDelegate::PostTouchRequest().
virtual void AAX_CStatelessParameter::Release () inline virtual
Signals the automation system that a control has been released.
Call this method in response to GUI events that complete editing, such as a mouse up. Once this method has been called you should not call SetNormalizedValue() again until after the next call to Touch().
Implements AAX_IParameter.
References Identifier(), mAutomationDelegate, and AAX_IAutomationDelegate::PostReleaseRequest().
virtual void AAX_CStatelessParameter::SetNormalizedValue (double newNormalizedValue) inline virtual
Sets a parameter value using it's normalized representation.
For more information regarding normalized values, see Parameter Manager
Parameters
[in] newNormalizedValue New value (normalized) to which the parameter will be set
Implements AAX_IParameter.
virtual double AAX_CStatelessParameter::GetNormalizedValue () const inline virtual
Returns the normalized representation of the parameter's current real value.
Implements AAX_IParameter.
virtual void AAX_CStatelessParameter::SetNormalizedDefaultValue (double normalizedDefault) inline virtual
Sets the parameter's default value using its normalized representation.
Implements AAX_IParameter.
virtual double AAX_CStatelessParameter::GetNormalizedDefaultValue () const inline virtual
Returns the normalized representation of the parameter's real default value.
Implements AAX_IParameter.
virtual void AAX_CStatelessParameter::SetToDefaultValue () inline virtual
Restores the state of this parameter to its default value.
Implements AAX_IParameter.
virtual void AAX_CStatelessParameter::SetNumberOfSteps (uint32_t numSteps) inline virtual
Sets the number of discrete steps for this parameter.
Stepped parameter values are useful for discrete parameters and for "jumping" events such as mouse wheels, page up/down, etc. The parameter's step size is used to specify the coarseness of those changes.
Note
numSteps MUST be greater than zero. All other values may be considered an error by the host.
Parameters
[in] numSteps The number of steps that the parameter will use
Implements AAX_IParameter.
virtual uint32_t AAX_CStatelessParameter::GetNumberOfSteps () const inline virtual
Returns the number of discrete steps used by the parameter.
See SetNumberOfSteps() for more information about parameter steps.
Implements AAX_IParameter.
virtual uint32_t AAX_CStatelessParameter::GetStepValue () const inline virtual
Returns the current step for the current value of the parameter.
See SetNumberOfSteps() for more information about parameter steps.
Implements AAX_IParameter.
virtual double AAX_CStatelessParameter::GetNormalizedValueFromStep (uint32_t iStep) const inline virtual
Returns the normalized value for a given step.
See SetNumberOfSteps() for more information about parameter steps.
Implements AAX_IParameter.
virtual uint32_t AAX_CStatelessParameter::GetStepValueFromNormalizedValue (double normalizedValue) const inline virtual
Returns the step value for a normalized value of the parameter.
See SetNumberOfSteps() for more information about parameter steps.
Implements AAX_IParameter.
virtual void AAX_CStatelessParameter::SetStepValue (uint32_t iStep) inline virtual
Returns the current step for the current value of the parameter.
See SetNumberOfSteps() for more information about parameter steps.
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::GetValueString (AAX_CString * valueString) const inline virtual
Serializes the parameter value into a string.
Parameters
[out] valueString A string representing the parameter's real value
Return values
true The string conversion was successful
false The string conversion was unsuccessful
Implements AAX_IParameter.
References mValueString.
virtual bool AAX_CStatelessParameter::GetValueString (int32_t iMaxNumChars, AAX_CString * valueString) const inline virtual
Serializes the parameter value into a string, size hint included.
Parameters
[in] iMaxNumChars A size hint for the size of the string being requested. Useful for control surfaces and other limited area text fields. (make sure that size of desired string also has room for null termination)
[out] valueString A string representing the parameter's real value
Return values
true The string conversion was successful
false The string conversion was unsuccessful
Implements AAX_IParameter.
References GetValueString().
Referenced by GetValueString().
virtual bool AAX_CStatelessParameter::GetNormalizedValueFromBool (bool value, double * normalizedValue) const inline virtual
Converts a bool to a normalized parameter value.
Parameters
[in] value A value for the parameter
[out] normalizedValue The normalized parameter value associated with value
Return values
true The value conversion was successful
false The value conversion was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::GetNormalizedValueFromInt32 (int32_t value, double * normalizedValue) const inline virtual
Converts an integer to a normalized parameter value.
Parameters
[in] value A value for the parameter
[out] normalizedValue The normalized parameter value associated with value
Return values
true The value conversion was successful
false The value conversion was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::GetNormalizedValueFromFloat (float value, double * normalizedValue) const inline virtual
Converts a float to a normalized parameter value.
Parameters
[in] value A value for the parameter
[out] normalizedValue The normalized parameter value associated with value
Return values
true The value conversion was successful
false The value conversion was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::GetNormalizedValueFromDouble (double value, double * normalizedValue) const inline virtual
Converts a double to a normalized parameter value.
Parameters
[in] value A value for the parameter
[out] normalizedValue The normalized parameter value associated with value
Return values
true The value conversion was successful
false The value conversion was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::GetNormalizedValueFromString (const AAX_CString & valueString, double * normalizedValue) const inline virtual
Converts a given string to a normalized parameter value.
Parameters
[in] valueString A string representing a possible real value for the parameter
[out] normalizedValue The normalized parameter value associated with valueString
Return values
true The string conversion was successful
false The string conversion was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::GetBoolFromNormalizedValue (double normalizedValue, bool * value) const inline virtual
Converts a normalized parameter value to a bool representing the corresponding real value.
Parameters
[in] normalizedValue The normalized value to convert
[out] value The converted value. Set only if conversion is successful.
Return values
true The conversion to bool was successful
false The conversion to bool was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::GetInt32FromNormalizedValue (double normalizedValue, int32_t * value) const inline virtual
Converts a normalized parameter value to an integer representing the corresponding real value.
Parameters
[in] normalizedValue The normalized value to convert
[out] value The converted value. Set only if conversion is successful.
Return values
true The conversion to int32_t was successful
false The conversion to int32_t was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::GetFloatFromNormalizedValue (double normalizedValue, float * value) const inline virtual
Converts a normalized parameter value to a float representing the corresponding real value.
Parameters
[in] normalizedValue The normalized value to convert
[out] value The converted value. Set only if conversion is successful.
Return values
true The conversion to float was successful
false The conversion to float was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::GetDoubleFromNormalizedValue (double normalizedValue, double * value) const inline virtual
Converts a normalized parameter value to a double representing the corresponding real value.
Parameters
[in] normalizedValue The normalized value to convert
[out] value The converted value. Set only if conversion is successful.
Return values
true The conversion to double was successful
false The conversion to double was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::GetStringFromNormalizedValue (double normalizedValue, AAX_CString & valueString) const inline virtual
Converts a normalized parameter value to a string representing the corresponding real value.
Parameters
[in] normalizedValue A normalized parameter value
[out] valueString A string representing the parameter value associated with normalizedValue
Return values
true The string conversion was successful
false The string conversion was unsuccessful
Implements AAX_IParameter.
References mValueString.
virtual bool AAX_CStatelessParameter::GetStringFromNormalizedValue (double normalizedValue, int32_t iMaxNumChars, AAX_CString & valueString) const inline virtual
Converts a normalized parameter value to a string representing the corresponding real, size hint included. value.
Parameters
[in] normalizedValue A normalized parameter value
[in] iMaxNumChars A size hint for the size of the string being requested. Useful for control surfaces and other limited area text fields. (make sure that size of desired string also has room for null termination)
[out] valueString A string representing the parameter value associated with normalizedValue
Return values
true The string conversion was successful
false The string conversion was unsuccessful
Implements AAX_IParameter.
References GetStringFromNormalizedValue().
Referenced by GetStringFromNormalizedValue().
virtual bool AAX_CStatelessParameter::SetValueFromString (const AAX_CString & newValueString) inline virtual
Converts a string to a real parameter value and sets the parameter to this value.
Parameters
[in] newValueString A string representing the parameter's new real value
Return values
true The string conversion was successful
false The string conversion was unsuccessful
Implements AAX_IParameter.
References mValueString.
virtual bool AAX_CStatelessParameter::GetValueAsBool (bool * value) const inline virtual
Retrieves the parameter's value as a bool.
Parameters
[out] value The parameter's real value. Set only if conversion is successful.
Return values
true The conversion to bool was successful
false The conversion to bool was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::GetValueAsInt32 (int32_t * value) const inline virtual
Retrieves the parameter's value as an int32_t.
Parameters
[out] value The parameter's real value. Set only if conversion is successful.
Return values
true The conversion to int32_t was successful
false The conversion to int32_t was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::GetValueAsFloat (float * value) const inline virtual
Retrieves the parameter's value as a float.
Parameters
[out] value The parameter's real value. Set only if conversion is successful.
Return values
true The conversion to float was successful
false The conversion to float was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::GetValueAsDouble (double * value) const inline virtual
Retrieves the parameter's value as a double.
Parameters
[out] value The parameter's real value. Set only if conversion is successful.
Return values
true The conversion to double was successful
false The conversion to double was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::GetValueAsString (AAX_IString * value) const inline virtual
Retrieves the parameter's value as a string.
Parameters
[out] value The parameter's real value. Set only if conversion is successful.
Return values
true The conversion to string was successful
false The conversion to string was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::SetValueWithBool (bool value) inline virtual
Sets the parameter's value as a bool.
Parameters
[out] value The parameter's real value. Set only if conversion is successful.
Return values
true The conversion from bool was successful
false The conversion from bool was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::SetValueWithInt32 (int32_t value) inline virtual
Sets the parameter's value as an int32_t.
Parameters
[out] value The parameter's real value. Set only if conversion is successful.
Return values
true The conversion from int32_t was successful
false The conversion from int32_t was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::SetValueWithFloat (float value) inline virtual
Sets the parameter's value as a float.
Parameters
[out] value The parameter's real value. Set only if conversion is successful.
Return values
true The conversion from float was successful
false The conversion from float was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::SetValueWithDouble (double value) inline virtual
Sets the parameter's value as a double.
Parameters
[out] value The parameter's real value. Set only if conversion is successful.
Return values
true The conversion from double was successful
false The conversion from double was unsuccessful
Implements AAX_IParameter.
virtual bool AAX_CStatelessParameter::SetValueWithString (const AAX_IString & value) inline virtual
Sets the parameter's value as a string.
Parameters
[out] value The parameter's real value. Set only if conversion is successful.
Return values
true The conversion from string was successful
false The conversion from string was unsuccessful
Implements AAX_IParameter.
References mValueString.
virtual void AAX_CStatelessParameter::SetType (AAX_EParameterType iControlType) inline virtual
Sets the type of this parameter.
See GetType for use cases
Parameters
[in] iControlType The parameter's new type as an AAX_EParameterType
Implements AAX_IParameter.
virtual AAX_EParameterType AAX_CStatelessParameter::GetType () const inline virtual
Returns the type of this parameter as an AAX_EParameterType.
Todo:
Document use cases for control type
Implements AAX_IParameter.
References AAX_eParameterType_Discrete.
virtual void AAX_CStatelessParameter::SetOrientation (AAX_EParameterOrientation iOrientation) inline virtual
Sets the orientation of this parameter.
Parameters
[in] iOrientation The parameter's new orientation
Implements AAX_IParameter.
virtual AAX_EParameterOrientation AAX_CStatelessParameter::GetOrientation () const inline virtual
Returns the orientation of this parameter.
Implements AAX_IParameter.
References AAX_eParameterOrientation_Default.
virtual void AAX_CStatelessParameter::SetTaperDelegate (AAX_ITaperDelegateBase & inTaperDelegate, bool inPreserveValue) inline virtual
Sets the parameter's taper delegate.
Parameters
[in] inTaperDelegate A reference to the parameter's new taper delegate
[in] inPreserveValue
Todo:
Document this parameter
Implements AAX_IParameter.
virtual void AAX_CStatelessParameter::SetDisplayDelegate (AAX_IDisplayDelegateBase & inDisplayDelegate) inline virtual
Sets the parameter's display delegate.
Parameters
[in] inDisplayDelegate A reference to the parameter's new display delegate
Implements AAX_IParameter.
virtual void AAX_CStatelessParameter::UpdateNormalizedValue (double newNormalizedValue) inline virtual
Sets the parameter's state given a normalized value.
This is the second half of the parameter setting operation that is initiated with a call to SetValue(). Parameters should not be set directly using this method; instead, use SetValue().
Parameters
[in] newNormalizedValue Normalized value that will be used to set the parameter's new state
Implements AAX_IParameter.
Member Data Documentation
AAX_CStringAbbreviations AAX_CStatelessParameter::mNames protected
Referenced by AddShortenedName(), ClearShortenedNames(), Name(), SetName(), and ShortenedName().
AAX_CString AAX_CStatelessParameter::mID protected
Referenced by Identifier().
AAX_IAutomationDelegate* AAX_CStatelessParameter::mAutomationDelegate protected
Referenced by Release(), SetAutomationDelegate(), and Touch().
AAX_CString AAX_CStatelessParameter::mValueString protected
Referenced by GetStringFromNormalizedValue(), GetValueString(), SetValueFromString(), and SetValueWithString().
The documentation for this class was generated from the following file:
AAX_CParameter.h