AAX SDK: AAX_CUnitPrefixDisplayDelegateDecorator< T > Class Template Reference
AAX_CUnitPrefixDisplayDelegateDecorator< T > Class Template Reference
AAX SDK Manual » AAX Library features » Parameter Manager » Display delegates » Display delegate decorators
#include <AAX_CUnitPrefixDisplayDelegateDecorator.h>
Description
template<typename T>
class AAX_CUnitPrefixDisplayDelegateDecorator< T >
A unit prefix decorator conforming to AAX_IDisplayDelegateDecorator.
This class is an AAX_IDisplayDelegateDecorator, meaning that it acts as a wrapper for other display delegates or concrete display types. For more information about display delegate decorators in AAX, see Display delegate decorators
The behavior of this class it to provide unit prefixes such as the k in kHz or the m in mm. It takes the value passed in and determines if the value is large or small enough to benefit from a unit modifier. If so, it adds that unit prefix character to the display string after scaling the number and calling deeper into the decorator pattern to get the concrete ValueToString() result.
The inverse is also supported, so if you type 1.5k in a text box and this decorator is in place, it should find the k and multiply the value by 1000 before converting it to a real value.
This decorator supports the following unit prefixes:
M (mega-)
k (kilo-)
m (milli-)
u (micro-)
Note
This class is not implemented for integer values as the conversions result in fractional numbers. Those would get truncated through the system and be pretty much useless.
Public Member Functions
AAX_CUnitPrefixDisplayDelegateDecorator (const AAX_IDisplayDelegate< T > &displayDelegate)
virtual AAX_CUnitPrefixDisplayDelegateDecorator< T > * Clone () const AAX_OVERRIDE
Constructs and returns a copy of the display delegate decorator.
virtual bool ValueToString (T value, AAX_CString *valueString) const AAX_OVERRIDE
Converts a string to a real parameter value.
virtual bool ValueToString (T value, int32_t maxNumChars, AAX_CString *valueString) const AAX_OVERRIDE
Converts a string to a real parameter value with a size constraint.
virtual bool StringToValue (const AAX_CString &valueString, T *value) const AAX_OVERRIDE
Converts a string to a real parameter value.
Public Member Functions inherited from AAX_IDisplayDelegateDecorator< T >
AAX_IDisplayDelegateDecorator (const AAX_IDisplayDelegate< T > &displayDelegate)
Constructor.
AAX_IDisplayDelegateDecorator (const AAX_IDisplayDelegateDecorator &other)
Copy constructor.
virtual ~AAX_IDisplayDelegateDecorator ()
Virtual destructor.
Public Member Functions inherited from AAX_IDisplayDelegateBase
virtual ~AAX_IDisplayDelegateBase ()
Virtual destructor.
Constructor & Destructor Documentation
template<typename T > AAX_CUnitPrefixDisplayDelegateDecorator< T >::AAX_CUnitPrefixDisplayDelegateDecorator (const AAX_IDisplayDelegate< T > & displayDelegate)
Member Function Documentation
template<typename T > AAX_CUnitPrefixDisplayDelegateDecorator< T > * AAX_CUnitPrefixDisplayDelegateDecorator< T >::Clone () const virtual
Constructs and returns a copy of the display delegate decorator.
In general, this method's implementation can use a simple copy constructor:
template <typename T>
AAX_CSubclassDisplayDelegate<T>*    AAX_CSubclassDisplayDelegate<T>::Clone() const
{
    return new AAX_CSubclassDisplayDelegate(*this);
}
Note
This is an idiomatic method in the decorator pattern, so watch for potential problems if this method is ever changed or removed.
Reimplemented from AAX_IDisplayDelegateDecorator< T >.
template<typename T > bool AAX_CUnitPrefixDisplayDelegateDecorator< T >::ValueToString (T value, AAX_CString * valueString) const virtual
Converts a string to a real parameter value.
Override of the AAX_IDisplayDelegate implementation to call into the wrapped object. Display delegate decorators should call into this implementation to pass ValueToString() calls on to the wrapped object after applying their own value-to-string decoration.
Parameters
[in] valueString The string that will be converted
[out] value The real parameter value corresponding to valueString
Return values
true The string conversion was successful
false The string conversion was unsuccessful
Reimplemented from AAX_IDisplayDelegateDecorator< T >.
References AAX::fabsf(), and AAX_IDisplayDelegateDecorator< T >::ValueToString().
template<typename T > bool AAX_CUnitPrefixDisplayDelegateDecorator< T >::ValueToString (T value, int32_t maxNumChars, AAX_CString * valueString) const virtual
Converts a string to a real parameter value with a size constraint.
Override of the AAX_IDisplayDelegate implementation to call into the wrapped object. Display delegate decorators should call into this implementation to pass ValueToString() calls on to the wrapped object after applying their own value-to-string decoration.
Parameters
[in] valueString The string that will be converted
[in] maxNumChars Size hint for the desired maximum number of characters in the string (not including null termination)
[out] value The real parameter value corresponding to valueString
Return values
true The string conversion was successful
false The string conversion was unsuccessful
Reimplemented from AAX_IDisplayDelegateDecorator< T >.
References AAX::fabsf(), and AAX_IDisplayDelegateDecorator< T >::ValueToString().
template<typename T > bool AAX_CUnitPrefixDisplayDelegateDecorator< T >::StringToValue (const AAX_CString & valueString, T * value) const virtual
Converts a string to a real parameter value.
Override of the DisplayDecorator implementation to call into the wrapped object. Display delegate decorators should call into this implementation to pass StringToValue() calls on to the wrapped object after applying their own string-to-value decoding.
Parameters
[in] valueString The string that will be converted
[out] value The real parameter value corresponding to valueString
Return values
true The string conversion was successful
false The string conversion was unsuccessful
Reimplemented from AAX_IDisplayDelegateDecorator< T >.
References AAX_CString::Erase(), AAX_CString::Length(), and AAX_IDisplayDelegateDecorator< T >::StringToValue().
The documentation for this class was generated from the following file:
AAX_CUnitPrefixDisplayDelegateDecorator.h