//	NoteNames.h - An array of note names.
//	--------------------------------------------------------------------------
//	Copyright (c) 2004 Niall Moody
//	
//	Permission is hereby granted, free of charge, to any person obtaining a
//	copy of this software and associated documentation files (the "Software"),
//	to deal in the Software without restriction, including without limitation
//	the rights to use, copy, modify, merge, publish, distribute, sublicense,
//	and/or sell copies of the Software, and to permit persons to whom the
//	Software is furnished to do so, subject to the following conditions:

//	The above copyright notice and this permission notice shall be included in
//	all copies or substantial portions of the Software.

//	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
//	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
//	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
//	THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
//	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
//	FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
//	DEALINGS IN THE SOFTWARE.
//	--------------------------------------------------------------------------

#ifndef NOTENAMES_H_
#define NOTENAMES_H_

const char noteNames[128][5] = //5 because of the NULL terminator...
{
	"Off ",
	"C-0 ",
	"C#0 ",
	"D-0 ",
	"d#0 ",
	"E-0 ",
	"F-0 ",
	"F#0 ",
	"G-0 ",
	"G#0 ",
	"A-0 ",
	"A#0 ",
	"B-0 ",
	"C-1 ",
	"C#1 ",
	"D-1 ",
	"D#1 ",
	"E-1 ",
	"F-1 ",
	"F#1 ",
	"G-1 ",
	"G#1 ",
	"A-1 ",
	"A#1 ",
	"B-1 ",
	"C-2 ",
	"C#2 ",
	"D-2 ",
	"D#2 ",
	"E-2 ",
	"F-2 ",
	"F#2 ",
	"G-2 ",
	"G#2 ",
	"A-2 ",
	"A#2 ",
	"B-2 ",
	"C-3 ",
	"C#3 ",
	"D-3 ",
	"D#3 ",
	"E-3 ",
	"F-3 ",
	"F#3 ",
	"G-3 ",
	"G#3 ",
	"A-3 ",
	"A#3 ",
	"B-3 ",
	"C-4 ",
	"C#4 ",
	"D-4 ",
	"D#4 ",
	"E-4 ",
	"F-4 ",
	"F#4 ",
	"G-4 ",
	"G#4 ",
	"A-4 ",
	"A#4 ",
	"B-4 ",
	"C-5 ",
	"C#5 ",
	"D-5 ",
	"D#5 ",
	"E-5 ",
	"F-5 ",
	"F#5 ",
	"G-5 ",
	"G#5 ",
	"A-5 ",
	"A#5 ",
	"B-5 ",
	"C-6 ",
	"C#6 ",
	"D-6 ",
	"D#6 ",
	"E-6 ",
	"F-6 ",
	"F#6 ",
	"G-6 ",
	"G#6 ",
	"A-6 ",
	"A#6 ",
	"B-6 ",
	"C-7 ",
	"C#7 ",
	"D-7 ",
	"D#7 ",
	"E-7 ",
	"F-7 ",
	"F#7 ",
	"G-7 ",
	"G#7 ",
	"A-7 ",
	"A#7 ",
	"B-7 ",
	"C-8 ",
	"C#8 ",
	"D-8 ",
	"D#8 ",
	"E-8 ",
	"F-8 ",
	"F#8 ",
	"G-8 ",
	"G#8 ",
	"A-8 ",
	"A#8 ",
	"B-8 ",
	"C-9 ",
	"C#9 ",
	"D-9 ",
	"D#9 ",
	"E-9 ",
	"F-9 ",
	"F#9 ",
	"G-9 ",
	"G#9 ",
	"A-9 ",
	"A#9 ",
	"B-9 ",
	"C-10",
	"C#10",
	"D-10",
	"D#10",
	"E-10",
	"F-10",
	"F#10"
};

#endif
